#!/bin/sh

# Process command line options-------------------------
__parse_cmd () {
    while [ $# -gt 0 ] ; do
        case "$1" in
            help)       __help
                        exit
                        ;;
            vsm)        __vsm "$@"
                        exit
                        ;;
            cbdpd)      __cbdpd "$@"
                        exit
                        ;;
        esac
        shift
    done
}
