#!/bin/sh

# Process command line options-------------------------
__parse_cmd () {
    while [ $# -gt 0 ] ; do
        case "$1" in
            help)       __help
                        exit
                        ;;
            vsm)        __vsm "$@"
                        exit
                        ;;
              *)        __usage
                        exit
                        ;;
        esac
        shift
    done
}
