#!/bin/sh
#-------------------------------------------------------------------------+
# Copyright (c) 2015-2016, touchstone
# All rightt reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted providing that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFItt; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

unset LC_ALL
unset LANG

PATH=${PATH}:/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin

if [ "${1}" = "--version" -o "${1}" = "version" ] ; then
    echo "touchstone 1.0.0 (2016/10/22)"
    exit 0
fi

# Check if libs are available
if [ -e "/usr/local/lib/tt" ] ; then
    LIB="/usr/local/lib/tt"
else
    echo "ERROR: missing libraries"
    exit 1
fi

# Source the libs needed to use the script
. "${LIB}/main_parser"
. "${LIB}/main_help"
. "${LIB}/vsm/vsm_parser"
. "${LIB}/vsm/vsm_get_jid"
. "${LIB}/vsm/vsm_get_path"
. "${LIB}/vsm/vsm_check_param_validity"
. "${LIB}/vsm/vsm_get_property"

if [ -z "$1" ] ; then
    __usage
    exit 0
fi

if [ "$1" == "help" ] ; then
    __help
    exit 0
fi

__parse_cmd "$@"
