#!/bin/sh

_vsm_jid(){
    local action="$2"
    if [ "$action" = "get" ]; then
        _check_parameter_validity "$@"
    else
        echo "The following action cant be performed : ${action}"
    fi
}


