#!/bin/sh

__cbdpd_job_id_path_list_by_config(){
	local job_id_path_list vsm_id config_path param

	vsm_id="$3"
	config_path="/etc/cbdpconf.xml"
	param="dsname"

	job_id_path_list="$(jexec $vsm_id cat $config_path | grep $param2 | grep -v grep | cut -d '"' -f 2)"
	
}


