#!/bin/sh

__cbdpd(){
    while [ $# -gt 0 ] ; do
        case "$1" in
            check)      __cbdpd_check "$@"
                        exit
                        ;;
           status)		__cbdpd_status "$@"
                        exit
                        ;;
        esac
        shift
    done
}

