#!/bin/sh

__cbdpd(){
    while [ $# -gt 0 ] ; do
        case "$1" in
            check)      __check "$@"
                        exit
                        ;;
        esac
        shift
    done
}

