#!/bin/sh

__cbdpd_job_id_path_list(){
	if [ "$2" != "--vsmid"]; then
		echo "Wrong parameters eneterd!!!"
		echo "Usage: escli cbdpd jobid path_list --vsmid <vsmid>"
	fi

	jobid_path_list_from_cbdpctl=__cbdpd_job_id_path_list_by_cbdpctl "$@"
    jobid_path_list_from_config=__cbdpd_job_id_path_list_by_config "$@"
}


