#!/bin/sh

__cbdpd_job_id_list_by_cbdpctl(){
	local job_id_list vsm_id param

	vsm_id="$3"
	param="Instance"

	job_id_list="$(jexec $vsm_id cbdpctl -c list | grep $param | grep -v grep | cut -d ':' -f 2)"
}


