#!/bin/sh

__cbdpd_status(){
	local argument vsm_id cmd_output vsm_ip

	argument="$2"
	vsm_id="$3"
	vsm_ip="$(jls -j $vsm_id -h ip4.addr | grep -v "ip4.addr" | grep -v grep)"

	if [ "$argument" != "--vsmid" ]; then
		echo "Parameter entered is not --vsmid"
		echo "USE INSTEAD : escli cbdpd status --vsmid <vsm_id>"
	else
		cmd_output="$(jexec $vsm_id ps aux | grep cbdpd | grep -v grep | awk '{print $11}')"
		
		if [ "$cmd_output" = "/sbin/cbdpd" ]; then
			echo "CBDPD running in JAIL_ID:$vsm_id VSM_IP:$vsm_ip."
		else
			echo "CBDPD not running in JAIL_ID:$vsm_id VSM_IP:$vsm_ip."
		fi
	fi	
}


