#!/bin/sh

__cbdpd_job_id_list_by_config(){
	local job_id_list vsm_id config_path param

	vsm_id="$3"
	config_path="/etc/cbdpconf.xml"
	param="instanceid"

	job_id_list="$(jexec $vsm_id cat $config_path | grep $param | grep -v grep | cut -d '"' -f 2)"
}


