#!/bin/sh

__cbdpd_check(){
	local jid_list cbdpd_status

	# Getting jail id list
	jid_list="$(escli vsm jail_id list)"
	parse_list="$(echo "$jid_list" | grep -v "JID" | xargs)"

	# Getting CBDPD running status
	for jids in $parse_list; do
		cbdpd_status="$(escli cbdpd status --jid $jids)"
		echo $cbdpd_status
	done
}


