#!/bin/sh

__cbdpd(){
    while [ $# -gt 0 ] ; do
        case "$1" in
           health)    __cbdpd_health_check
                        exit
                        ;;
           status)		__cbdpd_status "$@"
                        exit
                        ;;
           jobid)      __cbdpd_job_id "$@"
                        exit
                        ;;
        esac
        shift
    done
}
