#!/bin/sh

__cbdpd_job_id_status(){
	# TODO
	# Command to be use
	# 	jexec $vsm_id cbdpctl -c status -j $path -i $job_id_list | grep $param3 | awk '{print $2}'
	# Need to pass vsmid, jobid path and jobid's here
	
}


