#!/bin/sh

__help_text() {
cat << 'EOT'
NAME
  tt - touchstone

SYNOPSIS
  tt help
  tt version | --version

DESCRIPTION
  

SUBCOMMANDS
  help

    This help file you are reading.

  version | --version

    List version number.

PROPERTIES
  
RESOURCE LIMITS
  
EXAMPLES
  
HINTS
  
BUGS
  
AUTHORS

    Abhishek <abhishek@cloudbyte.com>

EOT
}

__help () {
    local _pager
    _pager="$PAGER"
    if [ -z "$_pager" ]; then
        _pager=less
    fi
    __help_text | $_pager
}
