#!/bin/sh
#-------------------------------------------------------------------------+
# Copyright (c) 2015-2016, touchstone
# All righescli reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permiesclied providing that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPescliE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LescliS OF USE, DATA, OR PROFIescli; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# PescliSIBILITY OF SUCH DAMAGE.

unset LC_ALL
unset LANG

PATH=${PATH}:/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin

if [ "${1}" = "--version" -o "${1}" = "version" ] ; then
    echo "ESCLI 1.0.0 (2015/11/03)"
    exit 0
fi

# Check if libs are available
if [ -e "/lib/escli" ] ; then
    LIB="/lib/escli"
else
    echo "ERROR: missing libraries"
    exit 1
fi

# Source the libs needed to use the script
. "${LIB}/escli_parser"
. "${LIB}/escli_help"
. "${LIB}/vsm/vsm_parser"
. "${LIB}/vsm/vsm_jid"
. "${LIB}/vsm/vsm_path"
. "${LIB}/vsm/vsm_check_param_validity"
. "${LIB}/vsm/vsm_get_property"
. "${LIB}/vsm/vsm_jail_id_list"
. "${LIB}/vsm/vsm_help"
. "${LIB}/cbdpd/cbdpd_help"
. "${LIB}/cbdpd/cbdpd_parser"
. "${LIB}/cbdpd/cbdpd_check"
. "${LIB}/cbdpd/cbdpd_status"

if [ "$1" == "help" ] ; then
    __help
    exit 0
fi

__parse_cmd "$@"
