#!/bin/sh

lib_dir='lib/escli'
man_dir='man/man8'
bin_dir='sbin'

echo
rm -rf /$lib_dir
rm -rf /$man_dir/escli.8.gz
rm -rf /$bin_dir/escli
echo "**** Uninstallation of ESCLI from ELASTISTOR NODE is SUCCESSFULL ****"

echo

read -p "Want to uninstall ESCLI from NODE VSM's too(y/n)?" choice
if [ "$choice" = "y" -o "$choice" = "Y" ]; then
	echo
	tenant_dir='/tenants'
	subs=`ls $tenant_dir`
	man_tdir='man'

	for i in $subs; do
	  rm -rf "$tenant_dir/$i/$lib_dir"
	  rm -rf "$tenant_dir/$i/$man_tdir"
	  rm -rf "$tenant_dir/$i/$bin_dir/escli"
	done
	echo "**** Uninstallation of ESCLI from ELASTISTOR NODE VSM'S SUCCESSFULL ****"
	echo
fi