#!/bin/sh

_get_property(){
    local property="$1"
    local ip_add="$4"

    if [ "$ip_add" = "" ]; then
        echo "VSM IP missing!!!"
        echo "E.g. tt vsm jid get --vsmip <vsm-ip>"
        break
    fi

    if [ "$property" = "jid" ]; then
        local jail_id="$(jls -N | grep -i "${ip_add}" | awk '{print $1}')"
        if [ "$jail_id" = "" ]; then
            echo "VSM IP entered is incorrect!!!"
            break
        else
            echo "${jail_id}"
        fi
    fi

    if [ "$property" = "path" ]; then
            local vsm_path="$(jls -N | grep -i "${ip_add}" | awk '{print $4}')"
            if [ "$vsm_path" = "" ]; then
                echo "VSM IP entered is incorrect!!!"
                break
            else
                echo "${vsm_path}"
            fi
    fi
}


