#!/bin/sh

__vsm_path(){
    local action="$2"
    if [ "$action" = "get" ]; then
        __vsm_check_parameter_validity "$@"
    else
        echo "The following action can't be performed : ${action}"
    fi
}
