#!/bin/sh

__vsm(){
    while [ $# -gt 0 ] ; do
        case "$1" in
            jid)       _vsm_jid "$@"
                        exit
                        ;;
            path)      _vsm_path "$@"
                        exit
                        ;;
        esac
        shift
    done
}

