#!/bin/sh

_vsm_jid(){
	while [ $# -gt 0 ] ; do
        case "$2" in
            get)       _check_parameter_validity "$@"
                        exit
                        ;;
            list)      _vsm_jid_list
                        exit
                        ;;
        esac
        shift
    done
}


