#!/bin/sh

__vsm_list(){
    local vsm_id cbdpd_running_status

    vsm_id="$(jls -N -h jid | grep -v jid | grep -v grep)"

    if [ "$vsm_id" = "" ]; then
    	echo "No VSMs present, create VSMs first!!!"
    	exit 1
    else
    	for id in $vsm_id; 
    	do
    		cbdpd_running_status="$(escli cbdpd status --vsmid $vsm_id)"
            echo cbdpd_running_status
            cbdpd_lsof_vsm_id="$(escli cbdpd lsof --vsmid $vsm_id)" #TODO
            echo cbdpd_lsof_vsm_id
            cbdpd_jobid_list="$(escli cbdpd jobid list --vsmid $vsm_id)"
            echo cbdpd_jobid_list
            
    	done 	
    fi
}


