#!/bin/sh

__vsm(){
    while [ $# -gt 0 ] ; do
        case "$1" in
            jid)       __vsm_jid "$@"
                        exit
                        ;;
            path)      __vsm_path "$@"
                        exit
                        ;;
            list)      __vsm_list "$@"
                        exit
                        ;;
        esac
        shift
    done
}

