#!/bin/sh

__vsm_jid(){
	while [ $# -gt 0 ] ; do
        case "$2" in
            get)       __vsm_check_parameter_validity "$@"
                        exit
                        ;;
            list)      __vsm_jid_list
                        exit
                        ;;
        esac
        shift
    done
}


