#!/bin/sh

__vsm_jail_id(){
	while [ $# -gt 0 ] ; do
        case "$2" in
            get)       __vsm_check_parameter_validity "$@"
                        exit
                        ;;
        esac
        shift
    done
}


